name: gtrack_nartec
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.3.0
  # # flutter_native_splash: ^2.2.19
  loading_animation_widget: ^1.3.0
  email_validator: ^3.0.0
  fluttertoast: ^8.2.11
  provider: ^6.0.5
  awesome_dialog: ^3.2.1
  flutter_animate: ^4.5.2
  # nb_utils: ^7.1.1
  flutter_bloc: ^7.0.0
  # flutter_screenutil: ^5.9.3
  page_transition: ^2.2.1
  ionicons: ^0.2.2
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  dropdown_search: ^6.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  # flutter_barcode_scanner: ^2.0.0
  flutter_polyline_points: ^2.1.0
  # # flutter_blue: ^0.8.0
  # # zebra_rfid_sdk_plugin: ^0.0.3
  native_barcode_scanner: ^1.0.11
  gs1_barcode_parser: ^1.0.5
  shimmer: ^3.0.0
  flutter_simple_treeview: ^3.0.2
  # flutter_qr_code_scaner:
  pretty_qr_code: ^3.3.0
  permission_handler: ^11.3.1
  searchable_listview: ^2.16.0
  intl: ^0.20.2
  google_maps_directions: ^0.0.4
  image_picker: ^1.1.2
  flutter_typeahead: ^5.2.0
  http_parser: ^4.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.5.2
  # mobile_scanner: ^6.0.6
  icons_launcher: ^3.0.0
  logger: ^2.5.0
  barcode_widget: ^2.0.4
  easy_stepper: ^0.8.5+1
  mime: ^2.0.0
  syncfusion_flutter_pdfviewer: ^28.2.9
  url_launcher: ^6.3.1
  # flutter_pdfview: ^1.4.0
  # easy_pdf_viewer: ^1.0.8
  video_player: ^2.9.3
  chewie: ^1.10.0
  flutter_rating_bar: ^4.0.1
  location: ^5.0.0
  syncfusion_flutter_signaturepad: ^28.2.9
  path_provider: ^2.1.5
  equatable: ^2.0.7

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/glnpop/
